version: '3.9'
services:
  
  backend_blog:
    container_name: blog
    build:
      context: ./src/Blog.Backend
      dockerfile: Dockerfile
      args:
        - AZURE_KEY_VAULT_URL=arg_value
        - AZURE_CLIENT_ID=arg_value
        - AZURE_DIRECTORY_ID=arg_value
        - AZURE_CLIENT_SECRET=arg_value
    ports:
      - '5000:5000'
    restart: always