version: '3.9'
services:
  
  postgres_blog:
    image: postgres:latest
    container_name: postgres_blog
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=BlogDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: always
    volumes:
      - blog_db_data:/var/lib/postgresql/data
  
  backend_blog:
    container_name: backend_blog
    build:
      context: ./src/Blog.Backend
      dockerfile: Dockerfile
      args:
        - AZURE_KEY_VAULT_URL=arg_value
        - AZURE_CLIENT_ID=arg_value
        - AZURE_DIRECTORY_ID=arg_value
        - AZURE_CLIENT_SECRET=arg_value
    image: benotar/backend_blog
    ports:
      - '5000:5000'
    restart: on-failure
  
  frontend_blog:
    container_name: frontend_blog
    build:
      context: ./src/Blog.Frontend
      dockerfile: Dockerfile
    image: benotar/frontend_blog
    restart: on-failure
    ports:
      - '5173:5173'
    depends_on:
      - backend_blog
    environment:
      - VITE_API_URL=http://backend_blog:5000

volumes:
  blog_db_data: