name: Publish Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: blog-backend
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./src/Blog.Backend/Blog.Backend.sln

      - name: Build
        run: dotnet build ./src/Blog.Backend/Blog.Backend.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./src/Blog.Backend/Blog.Backend.sln --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish ./src/Blog.Backend/Blog.Backend.sln --configuration Release --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deployment
        uses: azure/webapps/deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}