name: Publish Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: blog-frontend
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    if: contains(github.event.head_commit.message, 'frontend')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
